os: windows
language: shell
env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
before_install:
  - choco install python --version 3.7.6
  - python -m pip install --upgrade pip
  - pip3 install pyinstaller
scirpt:
  - pyinstaller --one-file --windowed ssdr-client.py